SELECT	A.TITLE AS TITLE, 
A.BOARD_ID AS BOARD_ID, 
B.REPLY_ID AS REPLY_ID, 
B.WRITER_ID AS WRITER_ID, 
B.CONTENTS AS CONTENTS, 
TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
WHERE A.BOARD_ID = B.BOARD_ID
AND A.CREATED_DATE BETWEEN TO_DATE('2022-10-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
  ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;